### ISSUE TITLE
Propose technology and set it up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_skill_wiki#10]
What is a good choice of technology for the wiki system. We already have AngularJS for the accounting system and we have ReactJS for the web chat. Apart from choosing a framework that suits the purpose, we should also take into consideration that using either Angular or React would make it easier for contributors of the other components to collaborate in regards to technology insights.

**Comment by dynamitechetan** [comment]
https://vuejs.org/
https://vuematerial.github.io

I think Vue is lot easier than AngularJS or React and its performance is same as both of them.

**Comment by saurabhjn76** [comment]
@dynamitechetan Yes Vue.js would be a good option, it is lightweight & easy to learn.

**Comment by AliAyub007** [comment]
I don't have much knowledge about them but as far as I know and I have observed Vue js is better because it's good in performance it doesn't get slow with more number of watcher and its light weight as compared to others.

**Comment by DravitLochan** [comment]
Going with the discussion, vue2 is considered better than angular2. [see here](https://www.quora.com/What-is-the-difference-between-Angular-2-and-Vue-js-2/answer/Bipin-Pandey-7?srid=upSCo) But let's  broaden our search and do a little bit of research on if something else can be used.

**Comment by isuruAb** [comment]
Here are some Pros & Cons of Vue JS.
https://www.agriya.com/blog/2017/05/15/pros-and-cons-of-vue-js-framework/
I think Vue JS is good for this.

**Comment by mariobehling** [comment]
So, I am sitting together with @Orbiter and we are talking about the setup of the SUSI.AI components. 

Actually, there is an additional requirement that @Orbiter points out:

It should be possible to run the wiki and the web chat together as one component. Also, we want to produce reusable code across components, e.g. login functionality. Therefore, the wiki app should use the same technology as the chat app, which is ReactJS, and reuse the code as much as possible to progress quickly. 

Please implement the system in ReactJS and reuse login and other relevant components here as well.

**Comment by saurabhjn76** [comment]
:+1:
